/**
 * English → Chinese mood tag translation.
 *
 * Song profiles generated by LLM have English mood tags (melancholic, lonely, etc.)
 * but user input is Chinese ("无聊", "孤独", etc.).  This mapping lets the
 * scoring functions translate English tags to Chinese before matching, so
 * "无聊" can match a song tagged "melancholic".
 *
 * Keep it simple: one English tag → one or more Chinese equivalents.
 * No reverse mapping needed — user input is always Chinese.
 */

export const MOOD_EN_TO_ZH: Record<string, string[]> = {
  // Sad / low energy
  melancholic: ["忧郁", "伤感", "惆怅", "郁闷", "无聊"],
  melancholy: ["忧郁", "伤感", "惆怅"],
  sad: ["悲伤", "难过", "伤心"],
  sorrowful: ["悲伤", "哀伤"],
  lonely: ["孤独", "寂寞", "孤单", "无聊"],
  solitary: ["孤独", "寂寞", "孤单"],
  heartbroken: ["心碎", "失恋"],
  resigned: ["无奈", "认命", "妥协"],
  vulnerable: ["脆弱", "敏感"],
  wistful: ["怅惘", "若有所失"],

  // Nostalgic / reflective
  nostalgic: ["怀旧", "思念", "怀念"],
  contemplative: ["沉思", "冥想", "发呆"],
  introspective: ["内省", "沉思", "放空"],

  // Warm / hopeful
  warm: ["温暖", "温馨", "治愈"],
  tender: ["温柔", "柔和", "治愈"],
  hopeful: ["希望", "期待", "憧憬"],
  touching: ["感动", "触动", "催泪"],

  // Energetic / positive
  adventurous: ["冒险", "刺激", "探索"],
  triumphant: ["胜利", "凯旋", "自豪"],
  determined: ["坚定", "执着", "不屈"],
};

/**
 * Translate a list of mood tags: English tags get their Chinese equivalents
 * appended; Chinese tags pass through unchanged.
 */
export function translateMoodTags(tags: string[]): string[] {
  const result: string[] = [];
  for (const tag of tags) {
    result.push(tag);
    const zh = MOOD_EN_TO_ZH[tag.toLowerCase()];
    if (zh) result.push(...zh);
  }
  return result;
}
